# -*- coding: utf-8 -*-

"""
/***************************************************************************
 DeepLearningTools
                                 A QGIS plugin
 QGIS plugin to aid training Deep Learning Models
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-04-03
        copyright            : (C) 2020 by Philipe Borba
        email                : philipeborba@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QCoreApplication

import os
from collections import defaultdict
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterBoolean,
                       QgsProcessingException,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterExpression,
                       QgsProcessingParameterString,
                       QgsProcessingOutputVectorLayer,
                       QgsProcessingParameterExtent,
                       QgsFeatureRequest,
                       QgsProject,
                       QgsRasterLayer,
                       QgsExpression,
                       QgsExpressionContext,
                       QgsExpressionContextUtils,
                       QgsSpatialIndex
                       )
from DeepLearningTools.core.image_processing.image_utils import ImageUtils
from qgis.utils import iface


class CreateTrainTestSamplesAlgorithm(QgsProcessingAlgorithm):
    """
    Algorithm to group layers according to primitive, dataset and a category.
    INPUT_LAYERS: list of QgsVectorLayer
    CATEGORY_TOKEN: token used to split layer name
    CATEGORY_TOKEN_INDEX: index of the split list
    OUTPUT: list of outputs
    """
    INPUT = 'INPUT'
    SELECTED = 'SELECTED'
    TRAIN_PERCENTAGE = 'TRAIN_PERCENTAGE'
    TRAIN_DATASET = 'TRAIN_DATASET'
    TEST_DATASET = 'TEST_DATASET'
    def initAlgorithm(self, config):
        """
        Parameter setting.
        """
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT,
                self.tr('Input layer'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        self.addParameter(
            QgsProcessingParameterBoolean(
                self.SELECTED,
                self.tr('Process only selected features')
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.TRAIN_PERCENTAGE,
                self.tr('Train dataset percentage (test percentage will be the complement'),
                minValue=0,
                maxValue=1
            )
        )
        self.addOutput(
            QgsProcessingOutputVectorLayer(
                self.TRAIN_DATASET,
                self.tr('Train dataset')
            )
        )
        self.addOutput(
            QgsProcessingOutputVectorLayer(
                self.TEST_DATASET,
                self.tr('Test dataset')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        inputLyr = self.parameterAsVectorLayer(
            parameters,
            self.INPUT,
            context
        )
        if inputLyr is None:
            raise QgsProcessingException(
                self.invalidSourceError(
                    parameters,
                    self.INPUT
                )
            )
        onlySelected = self.parameterAsBool(
            parameters,
            self.SELECTED,
            context
        )
        trainPercentage = self.parameterAsDouble(
            parameters,
            self.TRAIN_PERCENTAGE,
            context
        )
        
        features = inputLyr.getFeatures() if not onlySelected \
            else inputLyr.getSelectedFeatures()
        #calculate size

        #remaining parameters

        #1. Buffer
        #2. Spatial Index
        #3.
        multiStepFeedback = QgsProcessingMultiStepFeedback(3, feedback)
        multiStepFeedback.setCurrentStep(0)
        output = procesing.run(
            "native:buffer"
            {
                'INPUT': features,
                'DISTANCE': -1,
                'SEGMENTS': 5,
                'END_CAP_STYLE': 0,
                'JOIN_STYLE': 0,
                'MITER_LIMIT': 2,
                'DISSOLVE': False,
                'OUTPUT': 'memory:'
            },
            context=context,
            feedback=multiStepFeedback
        )
        bufferLyr = output['OUTPUT']
        multiStepFeedback.setCurrentStep(1)
        spatialIdx, idDict = self.buildSpatialIndexAndIdDict(
            bufferLyr,
            feedback=multiStepFeedback
        )

        multiStepFeedback.setCurrentStep(2)
        progressStep = 100/bufferLyr.featureCount() \
            if bufferLyr.featureCount() !=0 else 0
        
        visitedSet = set()
        clusterSet = defaultdict(list)

        for current, feat in enumerate(featList):
            if feedback.isCanceled():
                break
            if feat.id() in visitedSet:
                feedback.setProgress(current*progressStep)
                continue

            feedback.setProgress(current*progressStep)
        return {self.OUTPUT: list(outputLayers.values())}
    
    def build_cluster(feat, clusterSet, visitedSet, spatialIdx, idDict):
        candidates = [featId for featId in spatialIdx.intersects(feat.geometry().boundingBox)]
        if candidates == [feat.id()]:
            visitedSet.add(feat.id())
            return
        else:


    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'createtraintestsamples'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('Create train test samples')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr('Dataset Tools')

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'datasettools'

    def tr(self, string):
        """
        Translates input string.
        """
        return QCoreApplication.translate('CreateTrainTestSamplesAlgorithm', string)

    def createInstance(self):
        """
        Creates an instance of this class
        """
        return CreateTrainTestSamplesAlgorithm()
